---
- name: "Provision image"
  hosts: default
  become: true

  tasks:
    - name: Install node
      yum:
        name: nodejs
        state: present
    - name: Install pulumi
      unarchive:
        src: https://get.pulumi.com/releases/sdk/pulumi-v3.61.0-linux-x64.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        owner: root
        group: root
        extra_opts: [--strip-components=1]
    - name: download code-server
      get_url:
        url: https://github.com/coder/code-server/releases/download/v4.11.0/code-server-4.11.0-amd64.rpm
        dest: /tmp/code-server-4.11.0-amd64.rpm
    - name: Install code-server
      yum:
        name: /tmp/code-server-4.11.0-amd64.rpm
        state: present
        disable_gpg_check: yes
    - name: Enable code-server
      systemd:
        name: code-server@ec2-user
        enabled: yes
        state: started
